"""Core module containing types, constants, exceptions, config, and logging."""

from katran.core.config import KatranConfig
from katran.core.constants import (
    CH_RINGS_SIZE,
    CTL_MAP_SIZE,
    DEFAULT_LRU_SIZE,
    MAX_REALS,
    MAX_SUPPORTED_CPUS,
    MAX_VIPS,
    RING_SIZE,
    STATS_MAP_SIZE,
    CtlArrayIndex,
    PacketFlags,
    Protocol,
    RealFlags,
    StatsCounterIndex,
    VipFlags,
)
from katran.core.exceptions import (
    BpfMapError,
    ConfigurationError,
    KatranError,
    MapNotFoundError,
    MapOperationError,
    RealError,
    RealExistsError,
    RealNotFoundError,
    ResourceExhaustedError,
    SerializationError,
    VipError,
    VipExistsError,
    VipNotFoundError,
)
from katran.core.logging import get_logger, setup_logging
from katran.core.types import (
    CtlValue,
    FlowKey,
    LbStats,
    Real,
    RealDefinition,
    RealPosLru,
    Vip,
    VipKey,
    VipMeta,
)

__all__ = [
    # Config & Logging
    "KatranConfig",
    "setup_logging",
    "get_logger",
    # Constants
    "RING_SIZE",
    "MAX_VIPS",
    "MAX_REALS",
    "MAX_SUPPORTED_CPUS",
    "CH_RINGS_SIZE",
    "STATS_MAP_SIZE",
    "CTL_MAP_SIZE",
    "DEFAULT_LRU_SIZE",
    "Protocol",
    "VipFlags",
    "RealFlags",
    "PacketFlags",
    "StatsCounterIndex",
    "CtlArrayIndex",
    # Types
    "VipKey",
    "VipMeta",
    "RealDefinition",
    "FlowKey",
    "RealPosLru",
    "CtlValue",
    "LbStats",
    "Vip",
    "Real",
    # Exceptions
    "KatranError",
    "BpfMapError",
    "MapNotFoundError",
    "MapOperationError",
    "SerializationError",
    "VipError",
    "VipExistsError",
    "VipNotFoundError",
    "RealError",
    "RealExistsError",
    "RealNotFoundError",
    "ResourceExhaustedError",
    "ConfigurationError",
]
