"""Core module containing types, constants, and exceptions."""

from katran.core.constants import (
    RING_SIZE,
    MAX_VIPS,
    MAX_REALS,
    MAX_SUPPORTED_CPUS,
    CH_RINGS_SIZE,
    STATS_MAP_SIZE,
    CTL_MAP_SIZE,
    DEFAULT_LRU_SIZE,
    Protocol,
    VipFlags,
    RealFlags,
    PacketFlags,
    StatsCounterIndex,
    CtlArrayIndex,
)
from katran.core.types import (
    VipKey,
    VipMeta,
    RealDefinition,
    FlowKey,
    RealPosLru,
    CtlValue,
    LbStats,
    Vip,
    Real,
)
from katran.core.exceptions import (
    KatranError,
    BpfMapError,
    MapNotFoundError,
    MapOperationError,
    SerializationError,
    VipError,
    VipExistsError,
    VipNotFoundError,
    RealError,
    RealExistsError,
    RealNotFoundError,
    ResourceExhaustedError,
    ConfigurationError,
)

__all__ = [
    # Constants
    "RING_SIZE",
    "MAX_VIPS",
    "MAX_REALS",
    "MAX_SUPPORTED_CPUS",
    "CH_RINGS_SIZE",
    "STATS_MAP_SIZE",
    "CTL_MAP_SIZE",
    "DEFAULT_LRU_SIZE",
    "Protocol",
    "VipFlags",
    "RealFlags",
    "PacketFlags",
    "StatsCounterIndex",
    "CtlArrayIndex",
    # Types
    "VipKey",
    "VipMeta",
    "RealDefinition",
    "FlowKey",
    "RealPosLru",
    "CtlValue",
    "LbStats",
    "Vip",
    "Real",
    # Exceptions
    "KatranError",
    "BpfMapError",
    "MapNotFoundError",
    "MapOperationError",
    "SerializationError",
    "VipError",
    "VipExistsError",
    "VipNotFoundError",
    "RealError",
    "RealExistsError",
    "RealNotFoundError",
    "ResourceExhaustedError",
    "ConfigurationError",
]
